apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-2jqe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-2jqe
    app.kubernetes.io/part-of: tkrw-pr712-0075-0010-app
  name: devfile-sample-2jqe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-2jqe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-2jqe
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0010-tenant/tkrw-pr712-0075-0010-app/devfile-sample-2jqe@sha256:8173cc84a7cefd872084efec94671163eb241d3764e8a70fdead2f2c7622bf68
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
